### ISSUE TITLE
some error in compliling

### ISSUE THREAD

**Issue by hoangnh1009** [jmdmahdi/ESP32-USB-TO-BLE#13]
Here is the error (Adruino IDE 2.3.3)
c:\Users\Hoang\Documents\Arduino\libraries\ESP32-USB-TO-BLE-master\BleDevice.cpp: In member function 'void BleDevice::begin()':
c:\Users\Hoang\Documents\Arduino\libraries\ESP32-USB-TO-BLE-master\BleDevice.cpp:130:3: error: 'BLEDevice' has not been declared
   BLEDevice::init(deviceName);
   ^~~~~~~~~
c:\Users\Hoang\Documents\Arduino\libraries\ESP32-USB-TO-BLE-master\BleDevice.cpp:131:24: error: 'BLEDevice' has not been declared
   BLEServer* pServer = BLEDevice::createServer();
                        ^~~~~~~~~

exit status 1

Compilation error: exit status 1

**Comment by rakshitbharat** [comment]
#14 try this PR

**Comment by rakshitbharat** [comment]
use latest vscode platform io ready source
