### ISSUE TITLE
Does This code work with mechanical keyboard?

### ISSUE THREAD

**Issue by jahidulislamjahid** [jmdmahdi/ESP32-USB-TO-BLE#18]
Hi there. I flashed an esp wroom32 (esp32 DevKit v1) about 3 weeks ago. code flashed successfully and I can connect it to my computer as an Esp32 keyboard but the issue is my keyboard. I have a mechanical keyboard. and I saw about a week or two ago a solution for the mechanical keyboard issue which referred to adding pull-up and pull-down resistors to the board. but lost the instruction and now I cannot find it. also, I see the project has been updated a few times. so I want to know is the updated code works with the mechanical keyboard as it is? or do I need the registers? If resistors are needed than can you kindly give me the instructions on how to do that?
and Thanks in advance.

**Comment by rakshitbharat** [comment]
Check read me properly and all closed issues you will find your answer,

thanks

**Comment by jahidulislamjahid** [comment]
Hi, I've got the instructions in a closed issue. but I'm not sure exactly where and in which file should I put those gpio codes. can you just tell me that. I have the required resistors. Just tell me where and in which file should I put these code. 
```// Configure pins as floating since we have external resistors
gpio_set_direction((gpio_num_t)16, GPIO_MODE_INPUT_OUTPUT);
gpio_set_direction((gpio_num_t)17, GPIO_MODE_INPUT_OUTPUT);
gpio_set_pull_mode((gpio_num_t)16, GPIO_FLOATING);
gpio_set_pull_mode((gpio_num_t)17, GPIO_FLOATING);
```


### And I am using this board.
![20241230_002451_lmc_8 4](https://github.com/user-attachments/assets/afe21d4b-aff0-4d16-bf29-d8b54c36898d)
![20241230_002549_lmc_8 4](https://github.com/user-attachments/assets/c3983431-13c2-4861-b4c8-793e8c14e50d)
