### ISSUE TITLE
How to detect keyboard

### ISSUE THREAD

**Issue by dienvx1997bn** [jmdmahdi/ESP32-USB-TO-BLE#3]
Hello jmdmahdi,
I 've just tried to test your project with my ESP32 board. But i can not detect my keyboard.
here is the log
![Screenshot 2024-05-12 232715](https://github.com/jmdmahdi/ESP32-USB-TO-BLE/assets/20875293/6a3b4568-2144-4a6a-bb2a-dfa0958726e4)

Could you make some short video to show how it works, It might help with me.

**Comment by jmdmahdi** [comment]
Hello,

Make sure you have connected D+ and D- correctly to GPIO16 and GPIO17 of your ESP32 module. Sometimes, the pin numbers on the module itself are different from the GPIO numbers. Double-check the ESP32 pinout diagram for your specific board to ensure you have the correct connections.

Additionally, ensure your 5-volt power supply is rated high enough to power both the ESP32 and your keyboard. If you are using a separate power supply for the keyboard, the ground of the keyboard power supply must be connected to the ESP32's supply ground.

Could you send some pictures of your setup? It would help in diagnosing the problem.

**Comment by rakshitbharat** [comment]
> Hello,
> 
> Make sure you have connected D+ and D- correctly to GPIO16 and GPIO17 of your ESP32 module. Sometimes, the pin numbers on the module itself are different from the GPIO numbers. Double-check the ESP32 pinout diagram for your specific board to ensure you have the correct connections.
> 
> Additionally, ensure your 5-volt power supply is rated high enough to power both the ESP32 and your keyboard. If you are using a separate power supply for the keyboard, the ground of the keyboard power supply must be connected to the ESP32's supply ground.
> 
> Could you send some pictures of your setup? It would help in diagnosing the problem.

I have done the same what you said but it don't work on mechanical keyboard
