### ISSUE TITLE
Rewrite to make Bluetooth to BLE

### ISSUE THREAD

**Issue by comk22** [jmdmahdi/ESP32-USB-TO-BLE#4]
Hi,
I have a Bluetooth keyboard which I want to make accessible on several devices. I don't know much about the code you use but I would give it a shot by using chatgpt 4 to rewrite the code to receive the signals from my Bluetooth keyboard Do you think this is doable or is your code too far away from this idea?

**Comment by jmdmahdi** [comment]
Hi,

For this project, we are sending keyboard data over BLE, so our current setup isn't designed to receive signals from a Bluetooth keyboard. However, I might be able to help you with your project. Please send me a message on Telegram so we can discuss it further.

Telegram ID: [@jmdmahdi](https://t.me/jmdmahdi)

Best regards.

**Comment by rakshitbharat** [comment]
#14 try this PR

**Comment by rakshitbharat** [comment]
latest source code have it with vscode platform io
