### ISSUE TITLE
Esp32 board v3.0.x compilation error 

### ISSUE THREAD

**Issue by masyam02** [jmdmahdi/ESP32-USB-TO-BLE#5]
Hi jmdmahdi
I've tried to make this project and i have some problems. I tried to upload the code but it kept showing some errors.
Then i tried to install esp32 board v2.0.x and the code uploaded successfully. Before this i used esp32 board v3.0.x
I tried to connect my esp32 to PC and it worked but my esp32 can't detect keyboard or mouse.

Thanks in advance

**Comment by rakshitbharat** [comment]
#14 try this PR
